/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as NormalRouteImport } from './routes/_normal'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as NormalSchedulerRouteImport } from './routes/_normal/scheduler'
import { Route as NormalProjectsIndexRouteImport } from './routes/_normal/projects/index'
import { Route as NormalProjectsProjectIDTasksIndexRouteImport } from './routes/_normal/projects/$projectID/tasks/index'
import { Route as NormalProjectsProjectIDTasksTaskIDRouteImport } from './routes/_normal/projects/$projectID/tasks/$taskID'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const NormalRoute = NormalRouteImport.update({
  id: '/_normal',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const NormalSchedulerRoute = NormalSchedulerRouteImport.update({
  id: '/scheduler',
  path: '/scheduler',
  getParentRoute: () => NormalRoute,
} as any)
const NormalProjectsIndexRoute = NormalProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => NormalRoute,
} as any)
const NormalProjectsProjectIDTasksIndexRoute =
  NormalProjectsProjectIDTasksIndexRouteImport.update({
    id: '/projects/$projectID/tasks/',
    path: '/projects/$projectID/tasks/',
    getParentRoute: () => NormalRoute,
  } as any)
const NormalProjectsProjectIDTasksTaskIDRoute =
  NormalProjectsProjectIDTasksTaskIDRouteImport.update({
    id: '/projects/$projectID/tasks/$taskID',
    path: '/projects/$projectID/tasks/$taskID',
    getParentRoute: () => NormalRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/signin': typeof SigninRoute
  '/scheduler': typeof NormalSchedulerRoute
  '/projects': typeof NormalProjectsIndexRoute
  '/projects/$projectID/tasks/$taskID': typeof NormalProjectsProjectIDTasksTaskIDRoute
  '/projects/$projectID/tasks': typeof NormalProjectsProjectIDTasksIndexRoute
}
export interface FileRoutesByTo {
  '/signin': typeof SigninRoute
  '/scheduler': typeof NormalSchedulerRoute
  '/projects': typeof NormalProjectsIndexRoute
  '/projects/$projectID/tasks/$taskID': typeof NormalProjectsProjectIDTasksTaskIDRoute
  '/projects/$projectID/tasks': typeof NormalProjectsProjectIDTasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRoute
  '/_normal': typeof NormalRouteWithChildren
  '/signin': typeof SigninRoute
  '/_normal/scheduler': typeof NormalSchedulerRoute
  '/_normal/projects/': typeof NormalProjectsIndexRoute
  '/_normal/projects/$projectID/tasks/$taskID': typeof NormalProjectsProjectIDTasksTaskIDRoute
  '/_normal/projects/$projectID/tasks/': typeof NormalProjectsProjectIDTasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/signin'
    | '/scheduler'
    | '/projects'
    | '/projects/$projectID/tasks/$taskID'
    | '/projects/$projectID/tasks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/signin'
    | '/scheduler'
    | '/projects'
    | '/projects/$projectID/tasks/$taskID'
    | '/projects/$projectID/tasks'
  id:
    | '__root__'
    | '/_admin'
    | '/_normal'
    | '/signin'
    | '/_normal/scheduler'
    | '/_normal/projects/'
    | '/_normal/projects/$projectID/tasks/$taskID'
    | '/_normal/projects/$projectID/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRoute
  NormalRoute: typeof NormalRouteWithChildren
  SigninRoute: typeof SigninRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_normal': {
      id: '/_normal'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof NormalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_normal/scheduler': {
      id: '/_normal/scheduler'
      path: '/scheduler'
      fullPath: '/scheduler'
      preLoaderRoute: typeof NormalSchedulerRouteImport
      parentRoute: typeof NormalRoute
    }
    '/_normal/projects/': {
      id: '/_normal/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof NormalProjectsIndexRouteImport
      parentRoute: typeof NormalRoute
    }
    '/_normal/projects/$projectID/tasks/': {
      id: '/_normal/projects/$projectID/tasks/'
      path: '/projects/$projectID/tasks'
      fullPath: '/projects/$projectID/tasks'
      preLoaderRoute: typeof NormalProjectsProjectIDTasksIndexRouteImport
      parentRoute: typeof NormalRoute
    }
    '/_normal/projects/$projectID/tasks/$taskID': {
      id: '/_normal/projects/$projectID/tasks/$taskID'
      path: '/projects/$projectID/tasks/$taskID'
      fullPath: '/projects/$projectID/tasks/$taskID'
      preLoaderRoute: typeof NormalProjectsProjectIDTasksTaskIDRouteImport
      parentRoute: typeof NormalRoute
    }
  }
}

interface NormalRouteChildren {
  NormalSchedulerRoute: typeof NormalSchedulerRoute
  NormalProjectsIndexRoute: typeof NormalProjectsIndexRoute
  NormalProjectsProjectIDTasksTaskIDRoute: typeof NormalProjectsProjectIDTasksTaskIDRoute
  NormalProjectsProjectIDTasksIndexRoute: typeof NormalProjectsProjectIDTasksIndexRoute
}

const NormalRouteChildren: NormalRouteChildren = {
  NormalSchedulerRoute: NormalSchedulerRoute,
  NormalProjectsIndexRoute: NormalProjectsIndexRoute,
  NormalProjectsProjectIDTasksTaskIDRoute:
    NormalProjectsProjectIDTasksTaskIDRoute,
  NormalProjectsProjectIDTasksIndexRoute:
    NormalProjectsProjectIDTasksIndexRoute,
}

const NormalRouteWithChildren =
  NormalRoute._addFileChildren(NormalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRoute,
  NormalRoute: NormalRouteWithChildren,
  SigninRoute: SigninRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
