@startuml
skinparam Style strictuml
skinparam SequenceMessageAlignment center

actor Student
actor "User (Student/Supervisor)" as U
participant "TaskDeliverableService" as TDS
participant "ProjectTaskService" as PTS
participant "ProjectService" as PS
participant "NotificationService" as NS

Student -> TDS : UploadDeliverable(userID, projectID, taskID, file)
activate TDS
    note right of TDS : Check if the file is a valid PDF
    
    TDS -> PTS : task := GetProjectTask\n(userID, projectID, taskID)
    
    create participant "d : Deliverable" as D
    TDS -> D : new Deliverable(file, filename, taskID, userID)
    
    note right of TDS : task.StagedDeliverableID := d.DeliverableID
    
    TDS --> Student : Deliverable
deactivate TDS

Student -> TDS : SubmitStagedDeliverable(userID, projectID, taskID)
activate TDS
    TDS -> PS : project := GetProject(userID, projectID)
    TDS -> PTS : task := GetProjectTask\n(userID, projectID, taskID)
    
    alt task.IsLocked
        TDS --> Student : throw InvalidOperationException
    else task.StagedDeliverableID == null
        TDS --> Student : throw InvalidOperationException
    else feedback criteria not met
        TDS --> Student : throw InvalidOperationException
    else
        note right of TDS : **Transaction Start**
        note right of TDS : Remove Submitted Deliverable
        note right of TDS : task.SubmittedDeliverableID := task.StagedDeliverableID
        note right of TDS : task.StagedDeliverableID := null
        
        TDS -> NS : CreateTaskNotification(supervisor, student, task)
        note right of TDS : **Transaction Commit**
        
        TDS --> Student : void
    end
deactivate TDS

U -> TDS : GetSubmittedDeliverable(userID, projectID, taskID)
activate TDS
    note right of TDS
        Verify user belongs to the project 
        and fetch the submitted file
    end note
    TDS --> U : Deliverable
deactivate TDS

Student -> TDS : GetStagedDeliverable(userID, projectID, taskID)
activate TDS
    note right of TDS
        Verify userID == project.StudentID
        and fetch the staged file
    end note
    TDS --> Student : Deliverable
deactivate TDS

@enduml