@startuml
skinparam Style strictuml
skinparam SequenceMessageAlignment center

actor Supervisor
actor Student
actor "User (Student/Supervisor)" as U
participant "FeedbackService" as FS
participant "ProjectTaskService" as PTS

Supervisor -> FS : CreateFeedbackCriterion(userID, projectID, taskID, description)
activate FS
    FS -> PTS : task := GetProjectTask\n(userID, projectID, taskID)
    
    alt task has no submitted deliverable
        FS --> Supervisor : throw UnauthorizedAccessException
    else
        create participant "c : FeedbackCriterion" as C
        FS -> C : new FeedbackCriterion(description, taskID)
        FS --> Supervisor : void
    end
deactivate FS

U -> FS : GetFeedbackCriteria(userID, projectID, taskID)
activate FS
    note right of FS : Verify user is a member of project
    FS --> U : FeedbackCriterion[]
deactivate FS

Supervisor -> FS : EditFeedbackCriterion(userID, projectID, taskID, criterionID, description, status)
activate FS
    FS -> FS : c := GetFeedbackCriterion(criterionID)
    note right of FS : Verify userID is the assigned Supervisor
    
    note right of FS : Update details
    FS --> Supervisor : void
deactivate FS

Supervisor -> FS : DeleteFeedbackCriterion(userID, projectID, taskID, criterionID)
activate FS
    FS -> FS : c := GetFeedbackCriterion(criterionID)
    note right of FS : Verify userID is the assigned Supervisor
    
    note right of FS : Remove criterion from system
    FS --> Supervisor : void
deactivate FS

Student -> FS : OverrideFeedbackCriterion(userID, projectID, taskID, criterionID)
activate FS
    FS -> FS : c := GetFeedbackCriterion(criterionID)
    note right of FS
         Verify user is a student of
         the project
    end note
    note right of FS : c.Status := "overridden"
    FS --> Student : void
deactivate FS

@enduml