@startuml
skinparam Style strictuml
skinparam SequenceMessageAlignment center

actor User
participant "MeetingService" as MS
participant "ProjectTaskService" as PTS
participant "ReminderService" as RS
participant "MailService" as MLS

User -> MS : GetSupervisorMeetings(userID)
activate MS
    note right of MS
      Fetch project assignment entries by userID
    end note

    note right of MS
      Fetch all organized and
      attended meetings of supervisor(s)
    end note
    
    MS --> User : Meeting[]
deactivate MS

User -> MS : BookMeeting(organizerID, projectID, taskID, attendeeID, details)
activate MS
    MS -> PTS : task := GetProjectTask\n(organizerID, projectID, taskID)
    
    create participant "m : Meeting" as M
    MS -> M : new Meeting(organizerID, attendeeID, taskID, details)
    note right of MS : m.IsAccepted := false
    
    note right of MS : **Transaction Start**
    MS -> RS : CreateMeetingReminders(m.Organizer, m.Attendee, m)
    MS -> MLS : CreateAndEnqueueMeetingMail(m.Organizer, m.Attendee, m)
    note right of MS : **Transaction Commit**
    
    MS --> User : void
deactivate MS

User -> MS : AcceptMeeting(userID, meetingID)
activate MS
    MS -> MS : m := GetSupervisorMeeting(meetingID)
    
    note right of MS
        Ensure the userID matches 
        the meeting AttendeeID
    end note
    
    note right of MS : m.IsAccepted = true
    note right of MS : **Transaction Start**
    MS -> MLS : CreateAndEnqueueMeetingMail(m.Organizer, m.Attendee, m)
    note right of MS : **Transaction Commit**
    
    MS --> User : void
deactivate MS

User -> MS : CancelMeeting(userID, meetingID)
activate MS
    MS -> MS : m := GetSupervisorMeeting(meetingID)
    
    note right of MS
        Ensure the userID matches 
        the meeting OrganizerID
    end note
    
    create participant "m : Meeting" as M
    note right of MS : **Transaction Start**
    MS -> RS : DeleteMeetingReminders(m)
    MS -> MLS : CreateAndEnqueueMeetingMail(m.Organizezr, m.Attendee, m)
    MS -> M : Delete Meeting
    destroy M
    
    note right of MS : **Transaction Commit**
    
    MS --> User : void
deactivate MS

User -> MS : RejectMeeting(userID, meetingID)
activate MS
    MS -> MS : m := GetSupervisorMeeting(meetingID)
    
    note right of MS
        Ensure the userID matches 
        the meeting AttendeeID
    end note
    
    create participant "m : Meeting" as M
    note right of MS : **Transaction Start**
    MS -> RS : DeleteMeetingReminders(m)
    MS -> MLS : CreateAndEnqueueMeetingMail(m.Organizer, m.Attendee, m)
    MS -> M : Delete Meeting
    destroy M
    note right of MS : **Transaction Commit**
    
    MS --> User : void
deactivate MS

@enduml