@startuml
skinparam Style strictuml
skinparam SequenceMessageAlignment center

actor Admin
participant "ProjectService" as PS
participant "ReportService" as RS

Admin -> PS : CreateProject(supervisorID, title, description, studentID)
activate PS
    create participant "p : Project" as P
    PS -> P : new Project(title, supervisorID, studentID)
    PS --> Admin : void
deactivate PS

Admin -> PS : ArchiveProject(projectID)
activate PS
    PS -> PS : project := GetProject(projectID)
    note right of PS : project.IsArchived := true
    PS --> Admin : void
deactivate PS

Admin -> PS : RestoreProject(projectID)
activate PS
    PS -> PS : project := GetProject(projectID)
    
    alt supervisor or student is deleted
        PS --> Admin : throw Exception
    end
    note right of PS : project.IsArchived := false
    PS --> Admin : void
deactivate PS

Admin -> PS : GetProject(userID, projectID)
activate PS
    alt project = null
        PS --> Admin: throw UnauthorizedAccessException
    end
    PS --> Admin : project : Project
deactivate PS

Admin -> PS : GetProjectsWithCount(limit, offset)
activate PS
    note right of PS : Fetch all projects regardless of status
    PS --> Admin : (Project[], totalCount)
deactivate PS

Admin -> RS : IngestProjectSupervisionList(file)
activate RS
    
    note right of RS : Check if the file is a valid format
    
    note right of RS
        Pull project info from the file and match
        emails to existing User IDs
    end note

    note right of RS : Filter out projects that are already in the database

    loop for each new project, p
        create participant "newP : Project" as NP
        RS -> NP : new Project(p.title, p.studentID, p.supervisorID)
    end
    RS --> Admin : void
deactivate RS

@enduml