server {
    listen 80;
    client_max_body_size 50M;

    # Root directory where React build files are located
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Helper for API proxying if needed, or leave it to the external proxy
    location /api/ {
        proxy_pass http://dotnet-server:5081/;
        proxy_set_header Host $host;
    }
}

