events {}
http {
    include /etc/nginx/mime.types;
    
    server {
        listen 80;
        server_name 204.168.201.226;

        # Route API requests to the .NET container
        location /api/ {
            proxy_pass http://dotnet-server:5081/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }

        # Route everything else to the React Frontend
        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }
    }
}
