// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PMS.DatabaseContext;

#nullable disable

namespace PMS.Migrations
{
    [DbContext(typeof(PMSDbContext))]
    [Migration("20251221090657_FullSchemaBugFix")]
    partial class FullSchemaBugFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PMS.Models.Deliverable", b =>
                {
                    b.Property<long>("DeliverableID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("DeliverableID"));

                    b.Property<byte[]>("File")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SubmissionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("SubmittedByID")
                        .HasColumnType("bigint");

                    b.Property<long>("TaskID")
                        .HasColumnType("bigint");

                    b.HasKey("DeliverableID");

                    b.HasIndex("SubmittedByID");

                    b.HasIndex("TaskID");

                    b.ToTable("Deliverable");
                });

            modelBuilder.Entity("PMS.Models.FeedbackCriteria", b =>
                {
                    b.Property<long>("FeedbackCriteriaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("FeedbackCriteriaID"));

                    b.Property<long>("DeliverableID")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("ProvidedByID")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("FeedbackCriteriaID");

                    b.HasIndex("DeliverableID");

                    b.HasIndex("ProvidedByID");

                    b.ToTable("FeedbackCriteria");
                });

            modelBuilder.Entity("PMS.Models.Meeting", b =>
                {
                    b.Property<long>("MeetingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("MeetingID"));

                    b.Property<long>("AttendeeID")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("End")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("OrganizerID")
                        .HasColumnType("bigint");

                    b.Property<long>("ProjectID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Start")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MeetingID");

                    b.HasIndex("AttendeeID");

                    b.HasIndex("OrganizerID");

                    b.HasIndex("ProjectID");

                    b.ToTable("Meetings");

                    b.HasData(
                        new
                        {
                            MeetingID = 1L,
                            AttendeeID = 1L,
                            End = new DateTime(2025, 12, 20, 11, 0, 0, 0, DateTimeKind.Utc),
                            OrganizerID = 2L,
                            ProjectID = 1L,
                            Start = new DateTime(2025, 12, 20, 10, 0, 0, 0, DateTimeKind.Utc),
                            Status = "pending"
                        },
                        new
                        {
                            MeetingID = 2L,
                            AttendeeID = 2L,
                            End = new DateTime(2025, 12, 21, 15, 0, 0, 0, DateTimeKind.Utc),
                            OrganizerID = 1L,
                            ProjectID = 1L,
                            Start = new DateTime(2025, 12, 21, 14, 0, 0, 0, DateTimeKind.Utc),
                            Status = "pending"
                        },
                        new
                        {
                            MeetingID = 3L,
                            AttendeeID = 1L,
                            End = new DateTime(2025, 12, 22, 10, 30, 0, 0, DateTimeKind.Utc),
                            OrganizerID = 2L,
                            ProjectID = 1L,
                            Start = new DateTime(2025, 12, 22, 9, 30, 0, 0, DateTimeKind.Utc),
                            Status = "accepted"
                        },
                        new
                        {
                            MeetingID = 4L,
                            AttendeeID = 2L,
                            End = new DateTime(2025, 12, 23, 12, 0, 0, 0, DateTimeKind.Utc),
                            OrganizerID = 1L,
                            ProjectID = 1L,
                            Start = new DateTime(2025, 12, 23, 11, 0, 0, 0, DateTimeKind.Utc),
                            Status = "pending"
                        },
                        new
                        {
                            MeetingID = 5L,
                            AttendeeID = 3L,
                            End = new DateTime(2025, 12, 20, 14, 0, 0, 0, DateTimeKind.Utc),
                            OrganizerID = 2L,
                            ProjectID = 2L,
                            Start = new DateTime(2025, 12, 20, 13, 0, 0, 0, DateTimeKind.Utc),
                            Status = "accepted"
                        },
                        new
                        {
                            MeetingID = 6L,
                            AttendeeID = 2L,
                            End = new DateTime(2025, 12, 21, 11, 0, 0, 0, DateTimeKind.Utc),
                            OrganizerID = 3L,
                            ProjectID = 2L,
                            Start = new DateTime(2025, 12, 21, 10, 0, 0, 0, DateTimeKind.Utc),
                            Status = "pending"
                        },
                        new
                        {
                            MeetingID = 7L,
                            AttendeeID = 3L,
                            End = new DateTime(2025, 12, 22, 16, 0, 0, 0, DateTimeKind.Utc),
                            OrganizerID = 2L,
                            ProjectID = 2L,
                            Start = new DateTime(2025, 12, 22, 15, 0, 0, 0, DateTimeKind.Utc),
                            Status = "accepted"
                        },
                        new
                        {
                            MeetingID = 8L,
                            AttendeeID = 2L,
                            End = new DateTime(2025, 12, 23, 10, 0, 0, 0, DateTimeKind.Utc),
                            OrganizerID = 3L,
                            ProjectID = 2L,
                            Start = new DateTime(2025, 12, 23, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = "pending"
                        },
                        new
                        {
                            MeetingID = 9L,
                            AttendeeID = 4L,
                            End = new DateTime(2025, 12, 24, 11, 0, 0, 0, DateTimeKind.Utc),
                            OrganizerID = 5L,
                            ProjectID = 3L,
                            Start = new DateTime(2025, 12, 24, 10, 0, 0, 0, DateTimeKind.Utc),
                            Status = "accepted"
                        });
                });

            modelBuilder.Entity("PMS.Models.ProgressLogEntry", b =>
                {
                    b.Property<long>("ProgressLogEntryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ProgressLogEntryID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("MeetingID")
                        .HasColumnType("bigint");

                    b.Property<long>("ProjectID")
                        .HasColumnType("bigint");

                    b.Property<long?>("TaskID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ProgressLogEntryID");

                    b.HasIndex("MeetingID");

                    b.HasIndex("ProjectID");

                    b.HasIndex("TaskID");

                    b.ToTable("ProgressLogEntry");
                });

            modelBuilder.Entity("PMS.Models.Project", b =>
                {
                    b.Property<long>("ProjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ProjectID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("StudentID")
                        .HasColumnType("bigint");

                    b.Property<long?>("SupervisorID")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ProjectID");

                    b.HasIndex("StudentID");

                    b.HasIndex("SupervisorID");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            ProjectID = 1L,
                            Description = "Research on AI algorithms",
                            Status = "Active",
                            StudentID = 1L,
                            SupervisorID = 2L,
                            Title = "AI Research"
                        },
                        new
                        {
                            ProjectID = 2L,
                            Description = "Research on Optical Character Recognition",
                            Status = "Active",
                            StudentID = 3L,
                            SupervisorID = 2L,
                            Title = "OCR Research"
                        },
                        new
                        {
                            ProjectID = 3L,
                            Description = "Development of Blockchain applications",
                            Status = "Active",
                            StudentID = 4L,
                            SupervisorID = 5L,
                            Title = "Blockchain Dev"
                        });
                });

            modelBuilder.Entity("PMS.Models.Reminder", b =>
                {
                    b.Property<long>("ReminderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ReminderID"));

                    b.Property<long?>("MeetingID")
                        .HasColumnType("bigint");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("RecipientID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("RemindAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("TaskID")
                        .HasColumnType("bigint");

                    b.HasKey("ReminderID");

                    b.HasIndex("MeetingID");

                    b.HasIndex("RecipientID");

                    b.HasIndex("TaskID");

                    b.ToTable("Reminders");
                });

            modelBuilder.Entity("PMS.Models.Task", b =>
                {
                    b.Property<long>("TaskID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TaskID"));

                    b.Property<DateTime>("AssignedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ProjectID")
                        .HasColumnType("bigint");

                    b.Property<long?>("StagingDeliverableID")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("SubmittedDeliverableID")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TaskID");

                    b.HasIndex("ProjectID");

                    b.HasIndex("StagingDeliverableID");

                    b.HasIndex("SubmittedDeliverableID");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("PMS.Models.User", b =>
                {
                    b.Property<long>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("UserID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1L,
                            Email = "alice@uni.com",
                            IsDeleted = false,
                            Name = "Alice Student",
                            Password = "hashed_password",
                            Role = "Student"
                        },
                        new
                        {
                            UserID = 2L,
                            Email = "smith@uni.com",
                            IsDeleted = false,
                            Name = "Dr. Smith",
                            Password = "hashed_password",
                            Role = "Supervisor"
                        },
                        new
                        {
                            UserID = 3L,
                            Email = "hashim@uni.com",
                            IsDeleted = false,
                            Name = "Hashim",
                            Password = "hashed_password",
                            Role = "Student"
                        },
                        new
                        {
                            UserID = 4L,
                            Email = "charlie@uni.com",
                            IsDeleted = false,
                            Name = "Charlie Student",
                            Password = "hashed_password",
                            Role = "Student"
                        },
                        new
                        {
                            UserID = 5L,
                            Email = "brown@uni.com",
                            IsDeleted = false,
                            Name = "Dr. Brown",
                            Password = "hashed_password",
                            Role = "Supervisor"
                        });
                });

            modelBuilder.Entity("PMS.Models.Deliverable", b =>
                {
                    b.HasOne("PMS.Models.User", "SubmittedBy")
                        .WithMany("SubmittedDeliverables")
                        .HasForeignKey("SubmittedByID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PMS.Models.Task", "Task")
                        .WithMany("AllDeliverables")
                        .HasForeignKey("TaskID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubmittedBy");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("PMS.Models.FeedbackCriteria", b =>
                {
                    b.HasOne("PMS.Models.Deliverable", "Deliverable")
                        .WithMany("FeedbackCriterias")
                        .HasForeignKey("DeliverableID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PMS.Models.User", "ProvidedBy")
                        .WithMany("ProvidedFeedbackCriterias")
                        .HasForeignKey("ProvidedByID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deliverable");

                    b.Navigation("ProvidedBy");
                });

            modelBuilder.Entity("PMS.Models.Meeting", b =>
                {
                    b.HasOne("PMS.Models.User", "Attendee")
                        .WithMany("AttendedMeetings")
                        .HasForeignKey("AttendeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PMS.Models.User", "Organizer")
                        .WithMany("OrganizedMeetings")
                        .HasForeignKey("OrganizerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PMS.Models.Project", "Project")
                        .WithMany("Meetings")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attendee");

                    b.Navigation("Organizer");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PMS.Models.ProgressLogEntry", b =>
                {
                    b.HasOne("PMS.Models.Meeting", "Meeting")
                        .WithMany()
                        .HasForeignKey("MeetingID");

                    b.HasOne("PMS.Models.Project", "Project")
                        .WithMany("ProgressLogEntries")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PMS.Models.Task", "Task")
                        .WithMany("ProgressLogEntries")
                        .HasForeignKey("TaskID");

                    b.Navigation("Meeting");

                    b.Navigation("Project");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("PMS.Models.Project", b =>
                {
                    b.HasOne("PMS.Models.User", "Student")
                        .WithMany("ConductedProjects")
                        .HasForeignKey("StudentID");

                    b.HasOne("PMS.Models.User", "Supervisor")
                        .WithMany("SupervisedProjects")
                        .HasForeignKey("SupervisorID");

                    b.Navigation("Student");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("PMS.Models.Reminder", b =>
                {
                    b.HasOne("PMS.Models.Meeting", "Meeting")
                        .WithMany()
                        .HasForeignKey("MeetingID");

                    b.HasOne("PMS.Models.User", "Recipient")
                        .WithMany("Reminders")
                        .HasForeignKey("RecipientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PMS.Models.Task", "Task")
                        .WithMany("Reminders")
                        .HasForeignKey("TaskID");

                    b.Navigation("Meeting");

                    b.Navigation("Recipient");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("PMS.Models.Task", b =>
                {
                    b.HasOne("PMS.Models.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PMS.Models.Deliverable", "StagingDeliverable")
                        .WithMany()
                        .HasForeignKey("StagingDeliverableID");

                    b.HasOne("PMS.Models.Deliverable", "SubmittedDeliverable")
                        .WithMany()
                        .HasForeignKey("SubmittedDeliverableID");

                    b.Navigation("Project");

                    b.Navigation("StagingDeliverable");

                    b.Navigation("SubmittedDeliverable");
                });

            modelBuilder.Entity("PMS.Models.Deliverable", b =>
                {
                    b.Navigation("FeedbackCriterias");
                });

            modelBuilder.Entity("PMS.Models.Project", b =>
                {
                    b.Navigation("Meetings");

                    b.Navigation("ProgressLogEntries");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("PMS.Models.Task", b =>
                {
                    b.Navigation("AllDeliverables");

                    b.Navigation("ProgressLogEntries");

                    b.Navigation("Reminders");
                });

            modelBuilder.Entity("PMS.Models.User", b =>
                {
                    b.Navigation("AttendedMeetings");

                    b.Navigation("ConductedProjects");

                    b.Navigation("OrganizedMeetings");

                    b.Navigation("ProvidedFeedbackCriterias");

                    b.Navigation("Reminders");

                    b.Navigation("SubmittedDeliverables");

                    b.Navigation("SupervisedProjects");
                });
#pragma warning restore 612, 618
        }
    }
}
