// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PMS.DatabaseContext;

#nullable disable

namespace PMS.Migrations
{
    [DbContext(typeof(PMSDbContext))]
    [Migration("20260127101030_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PMS.Models.Deliverable", b =>
                {
                    b.Property<long>("DeliverableID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("DeliverableID"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("File")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SubmissionTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("SubmittedByID")
                        .HasColumnType("bigint");

                    b.Property<long>("TaskID")
                        .HasColumnType("bigint");

                    b.HasKey("DeliverableID");

                    b.HasIndex("SubmittedByID");

                    b.HasIndex("TaskID");

                    b.ToTable("Deliverables");
                });

            modelBuilder.Entity("PMS.Models.FeedbackCriterion", b =>
                {
                    b.Property<long>("FeedbackCriterionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("FeedbackCriterionID"));

                    b.Property<string>("ChangeObserved")
                        .HasColumnType("text");

                    b.Property<long>("DeliverableID")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("ProvidedByID")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("FeedbackCriterionID");

                    b.HasIndex("DeliverableID");

                    b.HasIndex("ProvidedByID");

                    b.ToTable("FeedbackCriterias");
                });

            modelBuilder.Entity("PMS.Models.Meeting", b =>
                {
                    b.Property<long>("MeetingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("MeetingID"));

                    b.Property<long>("AttendeeID")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("End")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("OrganizerID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Start")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("TaskID")
                        .HasColumnType("bigint");

                    b.HasKey("MeetingID");

                    b.HasIndex("AttendeeID");

                    b.HasIndex("OrganizerID");

                    b.HasIndex("TaskID");

                    b.ToTable("Meetings");

                    b.HasData(
                        new
                        {
                            MeetingID = 1L,
                            AttendeeID = 3L,
                            End = new DateTime(2026, 1, 30, 11, 0, 0, 0, DateTimeKind.Utc),
                            OrganizerID = 2L,
                            Start = new DateTime(2026, 1, 30, 10, 0, 0, 0, DateTimeKind.Utc),
                            Status = "pending",
                            TaskID = 1L
                        },
                        new
                        {
                            MeetingID = 2L,
                            AttendeeID = 2L,
                            End = new DateTime(2026, 1, 22, 15, 0, 0, 0, DateTimeKind.Utc),
                            OrganizerID = 3L,
                            Start = new DateTime(2026, 1, 22, 14, 0, 0, 0, DateTimeKind.Utc),
                            Status = "pending",
                            TaskID = 2L
                        },
                        new
                        {
                            MeetingID = 3L,
                            AttendeeID = 3L,
                            End = new DateTime(2026, 1, 30, 10, 30, 0, 0, DateTimeKind.Utc),
                            OrganizerID = 2L,
                            Start = new DateTime(2026, 1, 30, 9, 30, 0, 0, DateTimeKind.Utc),
                            Status = "accepted",
                            TaskID = 1L
                        },
                        new
                        {
                            MeetingID = 4L,
                            AttendeeID = 2L,
                            End = new DateTime(2026, 1, 23, 12, 0, 0, 0, DateTimeKind.Utc),
                            OrganizerID = 3L,
                            Start = new DateTime(2026, 1, 23, 11, 0, 0, 0, DateTimeKind.Utc),
                            Status = "rejected",
                            TaskID = 3L
                        });
                });

            modelBuilder.Entity("PMS.Models.Notification", b =>
                {
                    b.Property<long>("NotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("NotificationID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("RecipientID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("NotificationID");

                    b.HasIndex("RecipientID");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("PMS.Models.Project", b =>
                {
                    b.Property<long>("ProjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ProjectID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("StudentID")
                        .HasColumnType("bigint");

                    b.Property<long?>("SupervisorID")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ProjectID");

                    b.HasIndex("StudentID");

                    b.HasIndex("SupervisorID");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            ProjectID = 1L,
                            Description = "Research on AI algorithms",
                            Status = "active",
                            StudentID = 3L,
                            SupervisorID = 2L,
                            Title = "AI Research"
                        });
                });

            modelBuilder.Entity("PMS.Models.ProjectTask", b =>
                {
                    b.Property<long>("ProjectTaskID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ProjectTaskID"));

                    b.Property<long>("AssignedByID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean");

                    b.Property<long>("ProjectID")
                        .HasColumnType("bigint");

                    b.Property<long?>("StagedDeliverableID")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("SubmittedDeliverableID")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ProjectTaskID");

                    b.HasIndex("AssignedByID");

                    b.HasIndex("ProjectID");

                    b.HasIndex("StagedDeliverableID");

                    b.HasIndex("SubmittedDeliverableID");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            ProjectTaskID = 1L,
                            AssignedByID = 2L,
                            AssignedDate = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Review current papers on Transformer models.",
                            DueDate = new DateTime(2025, 11, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsLocked = false,
                            ProjectID = 1L,
                            Status = "completed",
                            Title = "Literature Review"
                        },
                        new
                        {
                            ProjectTaskID = 2L,
                            AssignedByID = 2L,
                            AssignedDate = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gather and clean the training dataset.",
                            DueDate = new DateTime(2026, 1, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsLocked = false,
                            ProjectID = 1L,
                            Status = "pending",
                            Title = "Dataset Collection"
                        },
                        new
                        {
                            ProjectTaskID = 3L,
                            AssignedByID = 2L,
                            AssignedDate = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Submit the formal research proposal.",
                            DueDate = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsLocked = false,
                            ProjectID = 1L,
                            Status = "missing",
                            Title = "Proposal Submission"
                        });
                });

            modelBuilder.Entity("PMS.Models.Reminder", b =>
                {
                    b.Property<long>("ReminderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ReminderID"));

                    b.Property<long?>("MeetingID")
                        .HasColumnType("bigint");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("RecipientID")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("RemindAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("TaskID")
                        .HasColumnType("bigint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ReminderID");

                    b.HasIndex("MeetingID");

                    b.HasIndex("RecipientID");

                    b.HasIndex("TaskID");

                    b.ToTable("Reminders");
                });

            modelBuilder.Entity("PMS.Models.User", b =>
                {
                    b.Property<long>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("UserID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1L,
                            Email = "admin@uni.com",
                            IsDeleted = false,
                            Name = "Admin",
                            Password = "$2a$12$FkZUs6elcp0MMrmAVvZXaud.SkwEG0JSQo0eQueIKmP63bHvbrK1m",
                            RefreshToken = "",
                            Role = "admin"
                        },
                        new
                        {
                            UserID = 2L,
                            Email = "jatooprashant099@gmail.com",
                            IsDeleted = false,
                            Name = "Dr. Smith",
                            Password = "$2a$12$FkZUs6elcp0MMrmAVvZXaud.SkwEG0JSQo0eQueIKmP63bHvbrK1m",
                            RefreshToken = "",
                            Role = "supervisor"
                        },
                        new
                        {
                            UserID = 3L,
                            Email = "prashant_pms@outlook.com",
                            IsDeleted = false,
                            Name = "Roland",
                            Password = "$2a$12$FkZUs6elcp0MMrmAVvZXaud.SkwEG0JSQo0eQueIKmP63bHvbrK1m",
                            RefreshToken = "",
                            Role = "student"
                        },
                        new
                        {
                            UserID = 4L,
                            Email = "prashant.jatoo@umail.uom.ac.mu",
                            IsDeleted = false,
                            Name = "Rebellius",
                            Password = "$2a$12$FkZUs6elcp0MMrmAVvZXaud.SkwEG0JSQo0eQueIKmP63bHvbrK1m",
                            RefreshToken = "",
                            Role = "student"
                        });
                });

            modelBuilder.Entity("PMS.Models.Deliverable", b =>
                {
                    b.HasOne("PMS.Models.User", "SubmittedBy")
                        .WithMany("SubmittedDeliverables")
                        .HasForeignKey("SubmittedByID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PMS.Models.ProjectTask", "Task")
                        .WithMany("AllDeliverables")
                        .HasForeignKey("TaskID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubmittedBy");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("PMS.Models.FeedbackCriterion", b =>
                {
                    b.HasOne("PMS.Models.Deliverable", "Deliverable")
                        .WithMany("FeedbackCriterias")
                        .HasForeignKey("DeliverableID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PMS.Models.User", "ProvidedBy")
                        .WithMany("ProvidedFeedbackCriterias")
                        .HasForeignKey("ProvidedByID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deliverable");

                    b.Navigation("ProvidedBy");
                });

            modelBuilder.Entity("PMS.Models.Meeting", b =>
                {
                    b.HasOne("PMS.Models.User", "Attendee")
                        .WithMany("AttendedMeetings")
                        .HasForeignKey("AttendeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PMS.Models.User", "Organizer")
                        .WithMany("OrganizedMeetings")
                        .HasForeignKey("OrganizerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PMS.Models.ProjectTask", "Task")
                        .WithMany("Meetings")
                        .HasForeignKey("TaskID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attendee");

                    b.Navigation("Organizer");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("PMS.Models.Notification", b =>
                {
                    b.HasOne("PMS.Models.User", "Recipient")
                        .WithMany("Notifications")
                        .HasForeignKey("RecipientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("PMS.Models.Project", b =>
                {
                    b.HasOne("PMS.Models.User", "Student")
                        .WithMany("ConductedProjects")
                        .HasForeignKey("StudentID");

                    b.HasOne("PMS.Models.User", "Supervisor")
                        .WithMany("SupervisedProjects")
                        .HasForeignKey("SupervisorID");

                    b.Navigation("Student");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("PMS.Models.ProjectTask", b =>
                {
                    b.HasOne("PMS.Models.User", "AssignedBy")
                        .WithMany("AssignedTasks")
                        .HasForeignKey("AssignedByID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PMS.Models.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PMS.Models.Deliverable", "StagedDeliverable")
                        .WithMany()
                        .HasForeignKey("StagedDeliverableID");

                    b.HasOne("PMS.Models.Deliverable", "SubmittedDeliverable")
                        .WithMany()
                        .HasForeignKey("SubmittedDeliverableID");

                    b.Navigation("AssignedBy");

                    b.Navigation("Project");

                    b.Navigation("StagedDeliverable");

                    b.Navigation("SubmittedDeliverable");
                });

            modelBuilder.Entity("PMS.Models.Reminder", b =>
                {
                    b.HasOne("PMS.Models.Meeting", "Meeting")
                        .WithMany()
                        .HasForeignKey("MeetingID");

                    b.HasOne("PMS.Models.User", "Recipient")
                        .WithMany("Reminders")
                        .HasForeignKey("RecipientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PMS.Models.ProjectTask", "Task")
                        .WithMany("Reminders")
                        .HasForeignKey("TaskID");

                    b.Navigation("Meeting");

                    b.Navigation("Recipient");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("PMS.Models.Deliverable", b =>
                {
                    b.Navigation("FeedbackCriterias");
                });

            modelBuilder.Entity("PMS.Models.Project", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("PMS.Models.ProjectTask", b =>
                {
                    b.Navigation("AllDeliverables");

                    b.Navigation("Meetings");

                    b.Navigation("Reminders");
                });

            modelBuilder.Entity("PMS.Models.User", b =>
                {
                    b.Navigation("AssignedTasks");

                    b.Navigation("AttendedMeetings");

                    b.Navigation("ConductedProjects");

                    b.Navigation("Notifications");

                    b.Navigation("OrganizedMeetings");

                    b.Navigation("ProvidedFeedbackCriterias");

                    b.Navigation("Reminders");

                    b.Navigation("SubmittedDeliverables");

                    b.Navigation("SupervisedProjects");
                });
#pragma warning restore 612, 618
        }
    }
}
