// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PMS.DatabaseContext;

#nullable disable

namespace PMS.Migrations
{
    [DbContext(typeof(PMSDbContext))]
    partial class PMSDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PMS.Models.Meeting", b =>
                {
                    b.Property<long>("MeetingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("MeetingID"));

                    b.Property<long>("AttendeeID")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("End")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("OrganizerID")
                        .HasColumnType("bigint");

                    b.Property<long>("ProjectID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Start")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MeetingID");

                    b.HasIndex("AttendeeID");

                    b.HasIndex("OrganizerID");

                    b.HasIndex("ProjectID");

                    b.ToTable("Meetings");

                    b.HasData(
                        new
                        {
                            MeetingID = 1L,
                            AttendeeID = 1L,
                            End = new DateTime(2025, 12, 20, 11, 0, 0, 0, DateTimeKind.Utc),
                            OrganizerID = 2L,
                            ProjectID = 1L,
                            Start = new DateTime(2025, 12, 20, 10, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Accepted"
                        },
                        new
                        {
                            MeetingID = 2L,
                            AttendeeID = 2L,
                            End = new DateTime(2025, 12, 21, 15, 0, 0, 0, DateTimeKind.Utc),
                            OrganizerID = 1L,
                            ProjectID = 1L,
                            Start = new DateTime(2025, 12, 21, 14, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Pending"
                        },
                        new
                        {
                            MeetingID = 3L,
                            AttendeeID = 1L,
                            End = new DateTime(2025, 12, 22, 10, 30, 0, 0, DateTimeKind.Utc),
                            OrganizerID = 2L,
                            ProjectID = 1L,
                            Start = new DateTime(2025, 12, 22, 9, 30, 0, 0, DateTimeKind.Utc),
                            Status = "Accepted"
                        },
                        new
                        {
                            MeetingID = 4L,
                            AttendeeID = 2L,
                            End = new DateTime(2025, 12, 23, 12, 0, 0, 0, DateTimeKind.Utc),
                            OrganizerID = 1L,
                            ProjectID = 1L,
                            Start = new DateTime(2025, 12, 23, 11, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Pending"
                        },
                        new
                        {
                            MeetingID = 5L,
                            AttendeeID = 3L,
                            End = new DateTime(2025, 12, 20, 14, 0, 0, 0, DateTimeKind.Utc),
                            OrganizerID = 2L,
                            ProjectID = 2L,
                            Start = new DateTime(2025, 12, 20, 13, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Accepted"
                        },
                        new
                        {
                            MeetingID = 6L,
                            AttendeeID = 2L,
                            End = new DateTime(2025, 12, 21, 11, 0, 0, 0, DateTimeKind.Utc),
                            OrganizerID = 3L,
                            ProjectID = 2L,
                            Start = new DateTime(2025, 12, 21, 10, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Pending"
                        },
                        new
                        {
                            MeetingID = 7L,
                            AttendeeID = 3L,
                            End = new DateTime(2025, 12, 22, 16, 0, 0, 0, DateTimeKind.Utc),
                            OrganizerID = 2L,
                            ProjectID = 2L,
                            Start = new DateTime(2025, 12, 22, 15, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Accepted"
                        },
                        new
                        {
                            MeetingID = 8L,
                            AttendeeID = 2L,
                            End = new DateTime(2025, 12, 23, 10, 0, 0, 0, DateTimeKind.Utc),
                            OrganizerID = 3L,
                            ProjectID = 2L,
                            Start = new DateTime(2025, 12, 23, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Pending"
                        },
                        new
                        {
                            MeetingID = 9L,
                            AttendeeID = 4L,
                            End = new DateTime(2025, 12, 24, 11, 0, 0, 0, DateTimeKind.Utc),
                            OrganizerID = 5L,
                            ProjectID = 3L,
                            Start = new DateTime(2025, 12, 24, 10, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Accepted"
                        });
                });

            modelBuilder.Entity("PMS.Models.Project", b =>
                {
                    b.Property<long>("ProjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ProjectID"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("StudentID")
                        .HasColumnType("bigint");

                    b.Property<long?>("SupervisorID")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("ProjectID");

                    b.HasIndex("StudentID");

                    b.HasIndex("SupervisorID");

                    b.HasIndex("UserID");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            ProjectID = 1L,
                            Status = "Active",
                            StudentID = 1L,
                            SupervisorID = 2L,
                            Title = "AI Research"
                        },
                        new
                        {
                            ProjectID = 2L,
                            Status = "Active",
                            StudentID = 3L,
                            SupervisorID = 2L,
                            Title = "OCR Research"
                        },
                        new
                        {
                            ProjectID = 3L,
                            Status = "Active",
                            StudentID = 4L,
                            SupervisorID = 5L,
                            Title = "Blockchain Dev"
                        });
                });

            modelBuilder.Entity("PMS.Models.User", b =>
                {
                    b.Property<long>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("UserID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1L,
                            Email = "alice@uni.com",
                            IsDeleted = false,
                            Name = "Alice Student",
                            Password = "hashed_password",
                            Role = "Student"
                        },
                        new
                        {
                            UserID = 2L,
                            Email = "smith@uni.com",
                            IsDeleted = false,
                            Name = "Dr. Smith",
                            Password = "hashed_password",
                            Role = "Supervisor"
                        },
                        new
                        {
                            UserID = 3L,
                            Email = "hashim@uni.com",
                            IsDeleted = false,
                            Name = "Hashim",
                            Password = "hashed_password",
                            Role = "Student"
                        },
                        new
                        {
                            UserID = 4L,
                            Email = "charlie@uni.com",
                            IsDeleted = false,
                            Name = "Charlie Student",
                            Password = "hashed_password",
                            Role = "Student"
                        },
                        new
                        {
                            UserID = 5L,
                            Email = "brown@uni.com",
                            IsDeleted = false,
                            Name = "Dr. Brown",
                            Password = "hashed_password",
                            Role = "Supervisor"
                        });
                });

            modelBuilder.Entity("PMS.Models.Meeting", b =>
                {
                    b.HasOne("PMS.Models.User", "Attendee")
                        .WithMany()
                        .HasForeignKey("AttendeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PMS.Models.User", "Organizer")
                        .WithMany()
                        .HasForeignKey("OrganizerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PMS.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attendee");

                    b.Navigation("Organizer");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PMS.Models.Project", b =>
                {
                    b.HasOne("PMS.Models.User", "Student")
                        .WithMany()
                        .HasForeignKey("StudentID");

                    b.HasOne("PMS.Models.User", "Supervisor")
                        .WithMany()
                        .HasForeignKey("SupervisorID");

                    b.HasOne("PMS.Models.User", null)
                        .WithMany("Projects")
                        .HasForeignKey("UserID");

                    b.Navigation("Student");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("PMS.Models.User", b =>
                {
                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
