services:
  postgres:
    image: postgres:alpine
    container_name: postgres_db_pms
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=joker1170
      - POSTGRES_DB=pms
    volumes:
      - postgres-data-pms:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d pms" ]
      interval: 5s
      timeout: 2s
      retries: 10

  dotnet-server:
    build:
      context: ./server
      target: production
    container_name: dotnet_server
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=joker1170
      - POSTGRES_DB=pms
      - POSTGRES_HOST=postgres
      - ASPNETCORE_URLS=http://+:5081
    depends_on:
      postgres:
        condition: service_healthy

  react:
    build:
      context: ./client
      target: production # This now triggers the Nginx-based build
    container_name: react_pms
    restart: always
    depends_on:
      - dotnet-server
    # No ports needed! The tunnel talks to port 80 internally.
  
  nginx-proxy:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro # For SSL keys
    depends_on:
      - dotnet-server
      - react

volumes:
  postgres-data-pms:
