events {}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # Redirect all HTTP traffic to HTTPS
    server {
        listen 80;
        server_name fypms.online www.fypms.online;
        return 301 https://$host$request_uri;
    }

    # HTTPS Server
    server {
        listen 443 ssl;
        server_name fypms.online www.fypms.online;

        ssl_certificate     /etc/letsencrypt/live/fypms.online/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/fypms.online/privkey.pem;

        # Optimization for React SPA
        location / {
            proxy_pass http://react:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location / {
            proxy_pass http://react:80;
        }
    }
}
