events {}
http {
    server {
        listen 80;
        server_name fypms.online www.fypms.online;

        location /api/ {
            proxy_pass http://dotnet-server:5081/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location / {
            proxy_pass http://react:80;
        }
    }
}